[project]
name = "diplom-igonin"
version = "0.1.0"
description = ""
authors = [
    {name = "Kostya Igonin",email = "Igoninqw@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django (>=6.0.1,<7.0.0)",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "drf-spectacular (>=0.29.0,<0.30.0)",
    "phonenumbers (>=9.0.22,<10.0.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)",
    "load-dotenv (>=0.1.0,<0.2.0)",
    "requests (>=2.32.5,<3.0.0)",
    "signals (>=0.0.2,<0.0.3)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
